name: py-lesson-dev
channels:
- conda-forge
- default
dependencies:
- python>=3.8
- pip

# Lesson packages
- altair
- jupyterlab
- pandas
- pyyaml

# Dev packages
- black
- jupyter_contrib_nbextensions
- jupyterlab-spellchecker
