name: py-lesson-dev
channels:
- conda-forge
- default
dependencies:
- python>=3.8
- pip

# Lesson packages
- altair
- jupyterlab
- pandas
- pyyaml=5.3.1
- textdistance=4.2.0

# Dev packages
- black
- jupyter_contrib_nbextensions
- jupyterlab-spellchecker

# pip packages
- pip:
  - glosario
